/**
* Pet project for tasks managment
* Declare Api between chat bot and server part
*
* OpenAPI spec version: 0.0.1
* Contact: bolik-u13@mail.ru
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "Role.h"

namespace io {
namespace swagger {
namespace server {
namespace model {

Role::Role()
{
    m_Rolename = "";
    m_RolenameIsSet = false;
    m_Description = "";
    m_DescriptionIsSet = false;
    
}

Role::~Role()
{
}

void Role::validate()
{
    // TODO: implement validation
}

nlohmann::json Role::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_RolenameIsSet)
    {
        val["rolename"] = ModelBase::toJson(m_Rolename);
    }
    if(m_DescriptionIsSet)
    {
        val["description"] = ModelBase::toJson(m_Description);
    }
    

    return val;
}

void Role::fromJson(nlohmann::json& val)
{
    if(val.find("rolename") != val.end())
    {
        setRolename(val.at("rolename"));
        
    }
    if(val.find("description") != val.end())
    {
        setDescription(val.at("description"));
        
    }
    
}


std::string Role::getRolename() const
{
    return m_Rolename;
}
void Role::setRolename(std::string value)
{
    m_Rolename = value;
    m_RolenameIsSet = true;
}
bool Role::rolenameIsSet() const
{
    return m_RolenameIsSet;
}
void Role::unsetRolename()
{
    m_RolenameIsSet = false;
}
std::string Role::getDescription() const
{
    return m_Description;
}
void Role::setDescription(std::string value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}
bool Role::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}
void Role::unsetDescription()
{
    m_DescriptionIsSet = false;
}

}
}
}
}

