/**
* Pet project for tasks managment
* Declare Api between chat bot and server part
*
* OpenAPI spec version: 0.0.1
* Contact: bolik-u13@mail.ru
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
/*
 * Role.h
 *
 * 
 */

#ifndef Role_H_
#define Role_H_


#include "ModelBase.h"

#include <string>

namespace io {
namespace swagger {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  Role
    : public ModelBase
{
public:
    Role();
    virtual ~Role();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Role members

    /// <summary>
    /// 
    /// </summary>
    std::string getRolename() const;
    void setRolename(std::string value);
    bool rolenameIsSet() const;
    void unsetRolename();
    /// <summary>
    /// 
    /// </summary>
    std::string getDescription() const;
    void setDescription(std::string value);
    bool descriptionIsSet() const;
    void unsetDescription();

protected:
    std::string m_Rolename;
    bool m_RolenameIsSet;
    std::string m_Description;
    bool m_DescriptionIsSet;
};

}
}
}
}

#endif /* Role_H_ */
