/**
* Pet project for tasks managment
* Declare Api between chat bot and server part
*
* OpenAPI spec version: 0.0.1
* Contact: bolik-u13@mail.ru
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#include "TaskInfo.h"

namespace io {
namespace swagger {
namespace server {
namespace model {

TaskInfo::TaskInfo()
{
    m_Id = 0L;
    m_IdIsSet = false;
    m_Priority = 0L;
    m_PriorityIsSet = false;
    m_Name = "";
    m_NameIsSet = false;
    m_Status = "";
    m_StatusIsSet = false;
    m_Usercreator = 0L;
    m_UsercreatorIsSet = false;
    m_Userexecutor = 0L;
    m_UserexecutorIsSet = false;
    m_Description = "";
    m_DescriptionIsSet = false;
    m_Stored = "";
    m_StoredIsSet = false;
    
}

TaskInfo::~TaskInfo()
{
}

void TaskInfo::validate()
{
    // TODO: implement validation
}

nlohmann::json TaskInfo::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_IdIsSet)
    {
        val["id"] = m_Id;
    }
    if(m_PriorityIsSet)
    {
        val["priority"] = m_Priority;
    }
    if(m_NameIsSet)
    {
        val["name"] = ModelBase::toJson(m_Name);
    }
    if(m_StatusIsSet)
    {
        val["status"] = ModelBase::toJson(m_Status);
    }
    if(m_UsercreatorIsSet)
    {
        val["usercreator"] = m_Usercreator;
    }
    if(m_UserexecutorIsSet)
    {
        val["userexecutor"] = m_Userexecutor;
    }
    if(m_DescriptionIsSet)
    {
        val["description"] = ModelBase::toJson(m_Description);
    }
    if(m_StoredIsSet)
    {
        val["stored"] = ModelBase::toJson(m_Stored);
    }
    

    return val;
}

void TaskInfo::fromJson(nlohmann::json& val)
{
    if(val.find("id") != val.end())
    {
        setId(val.at("id"));
    }
    if(val.find("priority") != val.end())
    {
        setPriority(val.at("priority"));
    }
    if(val.find("name") != val.end())
    {
        setName(val.at("name"));
        
    }
    if(val.find("status") != val.end())
    {
        setStatus(val.at("status"));
        
    }
    if(val.find("usercreator") != val.end())
    {
        setUsercreator(val.at("usercreator"));
    }
    if(val.find("userexecutor") != val.end())
    {
        setUserexecutor(val.at("userexecutor"));
    }
    if(val.find("description") != val.end())
    {
        setDescription(val.at("description"));
        
    }
    if(val.find("stored") != val.end())
    {
        setStored(val.at("stored"));
        
    }
    
}


int64_t TaskInfo::getId() const
{
    return m_Id;
}
void TaskInfo::setId(int64_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}
bool TaskInfo::idIsSet() const
{
    return m_IdIsSet;
}
void TaskInfo::unsetId()
{
    m_IdIsSet = false;
}
int64_t TaskInfo::getPriority() const
{
    return m_Priority;
}
void TaskInfo::setPriority(int64_t value)
{
    m_Priority = value;
    m_PriorityIsSet = true;
}
bool TaskInfo::priorityIsSet() const
{
    return m_PriorityIsSet;
}
void TaskInfo::unsetPriority()
{
    m_PriorityIsSet = false;
}
std::string TaskInfo::getName() const
{
    return m_Name;
}
void TaskInfo::setName(std::string value)
{
    m_Name = value;
    m_NameIsSet = true;
}
bool TaskInfo::nameIsSet() const
{
    return m_NameIsSet;
}
void TaskInfo::unsetName()
{
    m_NameIsSet = false;
}
std::string TaskInfo::getStatus() const
{
    return m_Status;
}
void TaskInfo::setStatus(std::string value)
{
    m_Status = value;
    m_StatusIsSet = true;
}
bool TaskInfo::statusIsSet() const
{
    return m_StatusIsSet;
}
void TaskInfo::unsetStatus()
{
    m_StatusIsSet = false;
}
int64_t TaskInfo::getUsercreator() const
{
    return m_Usercreator;
}
void TaskInfo::setUsercreator(int64_t value)
{
    m_Usercreator = value;
    m_UsercreatorIsSet = true;
}
bool TaskInfo::usercreatorIsSet() const
{
    return m_UsercreatorIsSet;
}
void TaskInfo::unsetUsercreator()
{
    m_UsercreatorIsSet = false;
}
int64_t TaskInfo::getUserexecutor() const
{
    return m_Userexecutor;
}
void TaskInfo::setUserexecutor(int64_t value)
{
    m_Userexecutor = value;
    m_UserexecutorIsSet = true;
}
bool TaskInfo::userexecutorIsSet() const
{
    return m_UserexecutorIsSet;
}
void TaskInfo::unsetUserexecutor()
{
    m_UserexecutorIsSet = false;
}
std::string TaskInfo::getDescription() const
{
    return m_Description;
}
void TaskInfo::setDescription(std::string value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}
bool TaskInfo::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}
void TaskInfo::unsetDescription()
{
    m_DescriptionIsSet = false;
}
std::string TaskInfo::getStored() const
{
    return m_Stored;
}
void TaskInfo::setStored(std::string value)
{
    m_Stored = value;
    m_StoredIsSet = true;
}
bool TaskInfo::storedIsSet() const
{
    return m_StoredIsSet;
}
void TaskInfo::unsetStored()
{
    m_StoredIsSet = false;
}

}
}
}
}

